server:
  port: 8181
spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.35.173.190:3306/store?characterEncoding=UTF-8
    username: root
    password: Tz!@12345678
    #    type: com.alibaba.druid.pool.DruidDataSource
#mybaties
mybatis:
  mapper-locations: classpath:/mapper/*.xml

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
# value
user:
  address:
    max-count: 20

#  type-aliases-package: com.tz.entity
#thymeleaf??
#  thymeleaf:
#    prefix:  classpath:/templates/
#    suffix: .html
#    servlet:
#      content-type: text/html
#    encoding: UTF-8
#    cache: false
#    mode: HTML

